import {getStore} from "@netlify/blobs";import crypto from "node:crypto";
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json",...C}});
const st=()=>getStore({name:"teacher-resources-hub-data"});
async function rd(k,d){return (await st().get(k,{type:"json"}))??d}async function wr(k,v){await st().setJSON(k,v)}
function sig(v){return v+"."+crypto.createHmac("sha256",process.env.ADMIN_SECRET||"change-me").update(v).digest("hex")}
function ok(r){let t=(r.headers.get("authorization")||"").replace("Bearer ",""),a=t.split(".");return a.length===2&&a[0].startsWith("admin-")&&a[1]===sig(a[0]).split(".")[1]}
function muli(q){q=q.toLowerCase();if(q.includes("scheme"))return"Teacher Muli: Start with learning outcomes, organise the term by weeks, add activities, resources and assessment evidence.";if(q.includes("lesson"))return"Teacher Muli: Use objective, prior knowledge, introduction, guided activity, learner practice, assessment, feedback and conclusion.";if(q.includes("assessment"))return"Teacher Muli: Mix recall, application and reasoning questions, with clear marks and a marking guide.";return"Teacher Muli: Tell me the grade, subject and topic and I will help with a scheme, lesson or assessment idea."}
export default async r=>{if(r.method==="OPTIONS")return new Response(null,{headers:C});let u=new URL(r.url),q=u.searchParams.get("route");try{
if(q==="resources"&&r.method==="GET")return J(await rd("resources",[{id:1,title:"Grade 5 Mathematics Term 1 Scheme",type:"Schemes of Work",grade:"Grade 5",price:30},{id:2,title:"Grade 4 Mathematics Lesson Plan",type:"Lesson Plans",grade:"Grade 4",price:30},{id:3,title:"Grade 6 End Term Assessment",type:"Assessments",grade:"Grade 6",price:50}]));
if(q==="login"){let b=await r.json();if(b.password!==process.env.ADMIN_PASSWORD)return J({error:"Invalid password"},401);return J({token:sig("admin-"+Date.now())})}
if(q==="payments"&&r.method==="GET"){if(!ok(r))return J({error:"Unauthorized"},401);let p=await rd("payments",[]),rs=await rd("resources",[]);return J(p.map(x=>({...x,resource_title:rs.find(y=>y.id==x.resource_id)?.title||"Unknown"})))}
if(q==="payments"&&r.method==="POST"){let b=await r.json();if(!b.name||!b.phone||!b.code||!b.resource_id)return J({error:"Complete payment details"},400);let p=await rd("payments",[]);p.push({id:Date.now().toString(),name:b.name,phone:b.phone,code:b.code,resource_id:b.resource_id,status:"PENDING"});await wr("payments",p);return J({ok:true})}
if(q==="status"){let code=u.searchParams.get("code"),p=(await rd("payments",[])).find(x=>x.code===code);if(!p)return J({error:"Transaction code not found"},404);return J({payment:{...p,download_url:p.status==="APPROVED"?`/.netlify/functions/api?route=download&id=${p.id}`:null}})}
if(q==="decision"){if(!ok(r))return J({error:"Unauthorized"},401);let b=await r.json(),p=await rd("payments",[]),x=p.find(y=>y.id==b.id);if(!x)return J({error:"Not found"},404);x.status=b.status;await wr("payments",p);return J({ok:true})}
if(q==="resources"&&r.method==="POST"){if(!ok(r))return J({error:"Unauthorized"},401);let b=await r.json(),id=Date.now().toString(),data=Buffer.from(b.data.split(",")[1],"base64");await st().set("file-"+id,data,{metadata:{contentType:b.mime||"application/octet-stream"}});let a=await rd("resources",[]);a.push({id,title:b.title,type:b.type,grade:b.grade||"",price:Number(b.price),name:b.name,mime:b.mime});await wr("resources",a);return J({ok:true})}
if(q==="download"){let p=(await rd("payments",[])).find(x=>x.id===u.searchParams.get("id"));if(!p||p.status!=="APPROVED")return J({error:"Payment not approved"},403);let r=(await rd("resources",[])).find(x=>x.id==p.resource_id),b=await st().get("file-"+r.id);if(!b)return J({error:"File not uploaded"},404);return new Response(b,{headers:{"Content-Type":r.mime||"application/octet-stream","Content-Disposition":`attachment; filename="${r.name||"resource"}"`,...C}})}
if(q==="muli"){let b=await r.json();return J({answer:muli(b.question||"")})}return J({error:"Not found"},404)}catch(e){return J({error:e.message},500)}}